### ISSUE TITLE
Add possibility to change keyboard / joystick mappings

### ISSUE THREAD

**Issue by laamaa** [laamaa/m8c#1]
The configuration could be initially done through a config file, at some point possibly from the application.

**Comment by laamaa** [comment]
#10 implements SDL Game Controllers for the program, meaning that most joypads should work now out of the box.
If bindings need to be changed, one can create a mapping string with external tools.

The keyboard thing must be still sorted out.

**Comment by peterswimm** [comment]
Can you point out what external tools we can use?

**Comment by laamaa** [comment]
https://generalarcade.com/gamepadtool/ haven't tested, but something like this should work

**Comment by laamaa** [comment]
Config file support implemented by JeffAlyanak
