### ISSUE TITLE
Windows 32 Bit Build?

### ISSUE THREAD

**Issue by 22bharris** [laamaa/m8c#109]
Is it possible to compile M8C to run on Windows 32 bit systems?  If so, how would I go about that?

Thanks!

**Comment by 22bharris** [comment]
Thank you very much!  I will try this out when I get home from work and will report back.

**Comment by 22bharris** [comment]
OK - I had a chance to try this on two different Windows 32 bit tablets tonight, with mixed results.  On the first tablet, no Teensy/M8 is recognized as connected.  On the second one, it shows the M8 display, I can move through the various screens, and pressing keys shows audio levels being output.  However, I don't hear any sound, despite changing the audio output device in Windows.  Any idea why this might be happening?  It is so close to working on this device!

Thanks again for your assistance!!

**Comment by laamaa** [comment]
Awesome! Glad to hear it works.
