### ISSUE TITLE
Flatpak

### ISSUE THREAD

**Issue by danbee** [laamaa/m8c#110]
Hi @laamaa. I've created a Flatpak manifest for M8c (https://github.com/danbee/m8c-flatpak), primarily so I can get it running on a Steam Deck more easily. I'd like to submit it to Flathub but wanted to make sure that was ok with you first.

**Comment by laamaa** [comment]
Feel free if you think it passes the requirements. I was thinking of doing a little GTK config ui for m8c and some point and flatpak the app, but no idea when I would have the time/inspiration for that :)

**Comment by laamaa** [comment]
Hi! Sorry for bothering, but I was wondering did you get ever get it submitted? I recently started using Fedora Silverblue and suddenly a flatpak version has become relevant to my interests :sweat_smile:

**Comment by laamaa** [comment]
Thanks for the writeup! Yeah, the udev rules and creating a new group for handling the permissions is a bit messy, and not very flatpak-style. Might be a better idea to try to make an automated AppImage build at some point to just gather all the dependencies together into a single package. :)
