### ISSUE TITLE
gamecontroller db in project is stale causing Xbox controller issues

### ISSUE THREAD

**Issue by SasquatchFuzz** [laamaa/m8c#112]
FYI - I was having quite a bit of trouble chasing down controller mapping issues tonight with an XBOX Series X controller and discovered the problem is a super stale db file in project.  This was causing the controller to get recognized as a "Zeroplus P4 Gamepad" and preventing me from mapping X/Y/A/B as option/edit/select start.  The fix was to copy over the following db

    https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt

and with that change the following now map properly:

- gamepad_up=11
- gamepad_left=13
- gamepad_down=12
- gamepad_right=14
- gamepad_select=0
- gamepad_start=1
- gamepad_opt=2
- gamepad_edit=3

**Comment by laamaa** [comment]
Thanks for the info, I saved a new version of the file to the repository.
