### ISSUE TITLE
Display issue on Anbernic RG353P

### ISSUE THREAD

**Issue by psederberg** [laamaa/m8c#115]
Hi!

I'm trying to get the latest m8c working on an ARM-based handheld device running the linux-based ArcOS. Earlier versions seem to compile and run reasonably well following the directions here: https://github.com/jasonporritt/rg351_m8c

I tried updating m8c to the latest version (pulled directly from this repo) in order to make use of the new features in the 3.1.1 firmware, including the direct audio mapping features, but despite compiling without error, I'm seeing this runtime error during startup and the display does not show up (or respond to input):

ERROR: Could not lock GBM surface front buffer

I'll start trying to track down if there are any significant changes to how the display buffer is instantiated, but I figured I would post the error here, too, in case the devs know of good places to look to track down the source of the error.

Thanks for any suggestions and please let me know if there is a better avenue for support!

Here's the full output during startup, which seems to progress normally up until the error:

```INFO: Reading config /home/ark/.local/share/m8c/config.ini
INFO: Writing config file to /home/ark/.local/share/m8c/config.ini
INFO: Looking for USB serial devices.
INFO: Found M8 in /dev/ttyACM0.
INFO: Opening port.
INFO: Looking for game controllers
INFO: Trying to open game controller database from /home/ark/.local/share/m8c/gamecontrollerdb.txt
INFO: Trying to open game controller database from /roms2/ports/M8/_m8c/gamecontrollerdb.txt
INFO: Found 569 game controller mappings
INFO: Enabling and resetting M8 display
INFO: Reset display
INFO: M8 Audio Input device found: M8, USB Audio
INFO: Opening audio devices
INFO: ** Hardware info ** Device type: Headless, Firmware ver 3.1.1
ERROR: Could not lock GBM surface front buffer
```

**Comment by laamaa** [comment]
Hi,

This issue sounds more related to the special hardware/system libraries than to m8c itself. The error is probably generated by SDL2 not being able to initialize the renderer. You could try asking in the M8 discord's headless thread if anyone else has encountered this, but unfortunately I'm unable to offer any assistance.
