### ISSUE TITLE
New gamecontrollerdb.txt causes button presses to do nothing on Anbernic RG351v

### ISSUE THREAD

**Issue by joedski** [laamaa/m8c#118]
- Hardware: Anbernic RG351v
- OS: ArkOS 2.0 02092023

Issue: on the latest revision, m8c will launch, connect to the headless Teensy, and show the UI; but button presses will do nothing.

Other discovery: The update to `gamecontrollerdb.txt` in commit c16e507cbccc207373997181781754e73465fb0d seems to be what cause button presses to do nothing.  However, I haven't done any work on figuring out what line or lines in that file caused this issue.

Workaround: Checking out the old version of `gamecontrollerdb.txt` fixes the issue, and copying that older version into the m8c SDL config dir at `~/.local/shared/m8c/` means subsequent updates to that file won't break things.

Not sure how much we want to care about this here, but I figured I'd at least put in an issue so it's captured somewhere.

**Comment by laamaa** [comment]
I seemed to mess up updating the DB previously as the file contained HTML characters. It should be the correct file now.
