### ISSUE TITLE
Raspberry pi 2B+ and m8c

### ISSUE THREAD

**Issue by Saddox** [laamaa/m8c#127]
https://www.youtube.com/watch?v=RhoN_KcZ6yE 

Works rather well but I do have some small issue with the sound via HDMI. Raspberry Linux OS straight out of the box. 
Is it totally hopeless to start learning to tweak the RPI 2B+?
Should I aim for a 3 or maybe 4?

The RPI will do nothing more than to show screen from M8, have a keaboard installed and a sound out (currently via HDMI). 
The idea is to make a box containing a smaller screen, connectors (sound/midi) somehow.. 

Any ideas, tips? Other Linux OS? Stronger coffee?`

Glad for any answer.

**Comment by laamaa** [comment]
Do you hear any other audio from the HDMI? The audio output device name can be set from config.ini if default doesn't work, maybe someone with a Pi setup would know  the device name.

**Comment by Saddox** [comment]
It's a standard installation so all system sounds are thru the Hdmi and so on. 
Youtube works.
There is sound from the M8 headless but somewhat crackling. Seems to vary deepning on the resolution on the screen.

**Comment by laamaa** [comment]
Ok, sounds like the easiest way is probably to get a more powerful machine. I personally don't recommend using a Pi for headless, usually it's just a major headache. An old laptop pc/mac works way better.

**Comment by Saddox** [comment]
> 

Yes, when I find a more powerful machine I will use that. But for now it will do. Good enough to have fun with, when using the right resolution.

**Comment by Saddox** [comment]
Solution: Low resolution on monitor and all seems fine :)
