### ISSUE TITLE
m8c with overlay file system enabled. 

### ISSUE THREAD

**Issue by ryancara** [laamaa/m8c#132]
Hi there, 

I'm trying to make a portable headless M8 using a Raspberry Pi Zero. 
So far, I've got almost everything working. However I'd like to enable the overlay file system (Read only mode), and when enabled Jack hangs when running this line 'jackd -d alsa -d hw:M8 -r44100 -p512 &'

Just wondering if you'd have any ideas or solutions to this? 

Cheers,

Ryan

**Comment by laamaa** [comment]
Hi!

Sorry, no idea. I didn't try to route audio back when I tried the software with a pi zero. First thing that comes to mind is that maybe the device is running out of memory because of the in-memory overlay filesystem? Have you tried if the internal audio routing in m8c would work instead?

-Jonne

**Comment by ryancara** [comment]
Hey I have not tried this! 
Are you referring to this section in the audio guide?:  

“Experimental audio routing support can be enabled by setting the config value "audio_enabled" to "true". The audio buffer size can also be tweaked from the config file for possible lower latencies. If the right audio device is not picked up by default, you can use a specific audio device by using "audio_output_device" config parameter.”

Ryan

**Comment by ryancara** [comment]
Okay an update: Using the experimental audio support, seems to work with OFS. However I'm getting clicks and pops that weren't present when using Jackd. I've tried a few different USB soundcards, but all have the same problem!

**Comment by laamaa** [comment]
Unfortunately I don't think there's much that can be done from m8c's side codewise, probably more related to the OS and kernel how effectively that stuff is handled... or at least I don't have the skills to help it :P

You could try increasing the audio buffer size in config.ini to 2048 for example (audio_buffer_size=2048) and see if that helps.
