### ISSUE TITLE
Jazzkeys S does nothing

### ISSUE THREAD

**Issue by jmolero** [laamaa/m8c#135]
Hello,

I have a problem with the jazzkeys and the `s` key, it doesn't trigger the D# note, it makes the screen flicker instead. Maybe it is doing the reset of the screen instead. 

I thought it may be because of my keys configuration but it happens also with the default one.

**Comment by jmolero** [comment]
I just saw the new release and I can confirm it is fixed. It was the `d` key that wasn't working I think, sorry about that. 

Thanks you!

**Comment by laamaa** [comment]
Oh right, forgot to comment back :P but yeah, it should be ok now. Thanks for reporting
