### ISSUE TITLE
Jazzkeys for keyboards without numpad

### ISSUE THREAD

**Issue by jmolero** [laamaa/m8c#136]
I have a request for the jazzkeys. I don't have a keyboard with numpad and can't change the octave and velocity. Could these be added to be available in smaller keyboards? I think it would be better if they can also be configurable like the rest.

**Comment by laamaa** [comment]
Sure it's possible to make them bindable. The current way how the configurable keybindings are done within the code is a bit laborious for all new additions... so unfortunately can't promise that I have time to do that. But if someone else wants to do it, I'll gladly accept a PR.

**Comment by jmolero** [comment]
For now it would be enough to just have them for both types of keyboards. It is ok for me if they are the same keys but without being in the numpad.

**Comment by laamaa** [comment]
Fixed with #143
