### ISSUE TITLE
What kind of keycode is used in configuration file for keyboard mappings?

### ISSUE THREAD

**Issue by proudhon** [laamaa/m8c#152]
Hello,

thanks for the incredibly useful work.

I cannot understand what kind of keycode is used by the configuration file, may you point it out in the documentation?

Thanks :)

**Comment by laamaa** [comment]
You can refer to https://www.freepascal-meets-sdl.net/sdl-2-0-scancode-lookup-table/ for the key scancodes

**Comment by proudhon** [comment]
Thanks!
