### ISSUE TITLE
quit from gamepad is not working

### ISSUE THREAD

**Issue by varoudis** [laamaa/m8c#158]
quitting with "analog stick click" does not work. used to be ok with older versions (1.7.1? 1.7.2?)
Was there a change?

**Comment by mnml** [comment]
I think the problem was introduced here: https://github.com/laamaa/m8c/blob/522c173084a23013912cf518c9fdafa18748632e/src/input.c#L435

**Comment by laamaa** [comment]
Dang, left that in by a mistake (was a unneccessary debug line), probably affects other stuff too.
