### ISSUE TITLE
m8c on WSL

### ISSUE THREAD

**Issue by parashu-rama** [laamaa/m8c#18]
Hello!
Try m8c on WSL2 - got CRITICAL: Cannot find a M8.
In WSL m8 serial /dev/ttyS*
https://www.scivision.dev/usb-tty-windows-subsystem-for-linux/
Is it possible to run m8c on Windows?

**Comment by laamaa** [comment]
I haven't tried building on WSL2, but looking at the error, I would imagine
that libserialport's USB device lookup isn't working in WSL2.

M8c can be built with MSYS2 in Windows and there is a prebuilt Windows
64bit binary available in the Releases section.

**Comment by parashu-rama** [comment]
Thank you very much!
