### ISSUE TITLE
[Raspberry Pi] Crash of the gui when using the fm synth 

### ISSUE THREAD

**Issue by klingklangmatze** [laamaa/m8c#24]
Thank you for this client!!. I have a problem when using the FM synths. As soon as I set complex waveforms, the gui disappears but the sound stays on. This happens particularly quickly when using noise. I can start the m8c again from the terminal, but after a few seconds it crashes again. Could it be because I am using an RPi4 instead of an RPi3b+?

**Comment by laamaa** [comment]
Hi, 

Thanks! The problem sounds weird. Unfortunately I currently do not have a Raspberry Pi 4 that I could test with, but I couldn't replicate the problem at least with my laptop. I'll test with a pi1 at some point if it happens with that.

**Comment by klingklangmatze** [comment]
Thank you for the feedback. Unfortunately, the error also occurs on a RPi3 B+ with a newly installed Raspberry Pi OS. I only use original RPi power supplies. 

I have also tested different M8 firmware versions  without success. As soon as the waveform of the FM synth becomes complex, the M8 interface closes to the Terminal, but the sound playback continues.
