### ISSUE TITLE
Unable to open M8C

### ISSUE THREAD

**Issue by ra1n5** [laamaa/m8c#39]
nathan@nathan-laptop:~/code/m8c$ ./m8c
INFO: Reading config /home/nathan/.local/share/m8c/config.ini
INFO: Looking for USB serial devices.
INFO: Found M8 in /dev/ttyACM0.
INFO: Opening port.
INFO: Enabling and resetting M8 display
INFO: Reset display
dbus[7724]: arguments to dbus_message_new_method_call() were incorrect, assertion "path != NULL" failed in file ../../../dbus/dbus-message.c line 1362.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
Aborted (core dumped)
nathan@nathan-laptop:~/code/m8c$

**Comment by laamaa** [comment]
Quick Googling of the error message suggests that the problem is with
something else than the program, most results suggest a faulty SDL2 package
within Ubuntu 18.04. With this amount of information I can only suggest
updating your system packages or maybe try compiling SDL2 from sources.
