### ISSUE TITLE
can't run m8c on Ubuntu  20.04.4 LTS

### ISSUE THREAD

**Issue by PyroXFire** [laamaa/m8c#43]
so as a Side effect of trying to get m8c to run on the pocketchip, I gave it a go on my laptop and it compiles fine and everything it finds the m8 then I get 

`ERROR: Error: Failed: Inappropriate ioctl for device`

not really sure what causes this. This doesn't happen on debian 11. I may try my other machine running lubuntu

**Comment by laamaa** [comment]
Please see https://github.com/laamaa/m8c/issues/20 if you need to manually compile libserialport

**Comment by PyroXFire** [comment]
yeah i think that is the case on my other machine running Lubuntu 21.10 it all works out of box. built m8c and it runs fine.
