### ISSUE TITLE
GamePi43 gamepad does not work

### ISSUE THREAD

**Issue by marcora** [laamaa/m8c#51]
I am trying to run m8c on a GamePi43 device <https://www.waveshare.com/wiki/GamePi43> using the RetroPie mkarcadejoystick driver <https://github.com/recalbox/mk_arcade_joystick_rpi>. The joystick works fine with any other app and I would greatly appreciate some help in making it work with m8c.

**Comment by laamaa** [comment]
Hi,

unfortunately I'm not familiar with Retropie or the gamepad in question. It
probably would at least need a line in the gamecontrollerdb.txt.

I think there are some code forks that are focused on getting the app
working on this kind of special systems like the piboy, you could try some
of those and see if they'd work for you.

**Comment by marcora** [comment]
Thanks for the pointers!!!
