### ISSUE TITLE
fullscreen=true doesn't work on raspberry bullseye

### ISSUE THREAD

**Issue by marcel-klasse** [laamaa/m8c#59]
Setting `fullscreen = true ` in `/home/<username>/.local/share/m8c/config.ini` doesn't trigger the program to start in fullscreen mode and disables the `alt + enter` control.

Model: Raspberry Pi 4 Model B Rev 1.2
OS: Debian GNU/Linux 11 (bullseye)

**Comment by laamaa** [comment]
Both things work on my Windows 11 laptop, could someone with a Pi please check?

**Comment by marcel-klasse** [comment]
to clarify: alt+enter works if fullscreen is set to false.

**Comment by db9979** [comment]
Worked on a bigger screen on my pi 
5 inch waveshare. Had only trouble with sound over the pi hdmi ( lags and hangs ) without m8c sound was ok.

**Comment by RowdyVoyeur** [comment]
I have exactly the same issue with Raspberry 4 Model B in Bullseye, i.e. fullscreen = true in config.ini does not start in fullscreen and disables Alt + Enter. I can't find a way to enable fullscreen mode.

**Comment by bloopclick** [comment]
Unable to duplicate on a 3B+ (Bullseye) with full KMS driver and Glamour enabled. Please try it with `use_gpu=false`.

**Comment by briwil** [comment]
`fullscreen = true` works correctly on my pi 4

**Comment by laamaa** [comment]
Are you still experiencing the issue? Since it seems to work for others, it might be specific to your setup.

**Comment by farvardin** [comment]
@marcel-klasse are you using x11 or wayland on your raspbian distribution? 

If unsure, give us the result of 

```
 echo $XDG_SESSION_TYPE
```

**Comment by laamaa** [comment]
Closing as inactive/cannot reproduce
