### ISSUE TITLE
With gamepad, have right stick do SELECT+up/down/left/right

### ISSUE THREAD

**Issue by YPares** [laamaa/m8c#68]
Hi! Thanks a lot for that software :)
Using a gamepad, it would be great to be able to use the right stick to navigate through menu (therefore acting like a SELECT+DPAD). Would that be difficult to implement?

**Comment by laamaa** [comment]
As the m8's own keycombos for navigation are already quite fast to use, I personally don't see much benefit from this and probably won't be implementing it.  

That being said, It should be possible by adding the relevant things to input.c in case you want to try it yourself.
