### ISSUE TITLE
Termux and/or Android support

### ISSUE THREAD

**Issue by xyproto** [laamaa/m8c#71]
Thanks for creating `m8c`! It's an amazing experience to try it out together with a Teensy 4.1 on Linux, and a great way to check out the Dirtywave M8 and "try before you buy".

I tried packaging `m8c` for Termux, but apparently packaging `libserialport` was not straightforward: https://github.com/termux/termux-packages/pull/9315

I also tried packaging m8c as an SDL2 application, for Android (as an `.apk` file), but including SDL2 in the various available Android build systems was more of a hassle than I had anticipated.

This is a feature request for somehow, either through Termux or as an Android application, support `m8c` on Android.

**Comment by laamaa** [comment]
Hi,

Thanks for checking out the program. As it would require significant
changes to the current visual layout and input system + an integrated audio
router to have a somewhat useful mobile app, it is probably easier to write
a new app from scratch using native Android things than port the
application directly - the protocol is quite simple. derkyjadex's
Webdisplay should work already on many devices, too.

**Comment by xyproto** [comment]
Sadly, derkyjadex/M8Webdisplay does not work on Android:

> The audio for Android is a known issue that I've described in the README. I'm not aware of any way of fixing it until Google changes the way that multiple audio devices are handled on Android and Chrome for Android.

https://github.com/derkyjadex/M8WebDisplay/issues/18#issuecomment-1134753313

**Comment by laamaa** [comment]
That's a bummer. You might be able to do the audio with some other program, if I remember correctly some people have been using Zenbeats for that.
