### ISSUE TITLE
Crash when selecting parameters to modulate

### ISSUE THREAD

**Issue by Actual-Guilll** [laamaa/m8c#75]
Hi !

First of all, thank you to the creators of this great software. 

On my Zorin 16 OS, it works very well but crashes every time I go to the screen where you select which parameter will be parameter-locked (the screen with the names of all available parameters). I hope I'm clear...  I know it's M8c crashing and not the M8, because the music continues to play, and when I relaunch m8c I'm still on the same page (and it crashes again after a few seconds if I don't leave this screen very fast).

Thank you !

**Comment by bloopclick** [comment]
@Actual-Guilll Can you provide a trace of the crash or any log messages that show up?

**Comment by Actual-Guilll** [comment]
Hi! I'm not sure how to do that, I'm kind of new to all this.

In the terminal windows it simply says :

INFO: Reading config /home/guilll/.local/share/m8c/config.ini
INFO: Writing config file to /home/guilll/.local/share/m8c/config.ini
INFO: Looking for USB serial devices.
INFO: Found M8 in /dev/ttyACM0.
INFO: Opening port.
INFO: Enabling and resetting M8 display
INFO: Reset display
INFO: Shutting down
INFO: Disconnecting M8

The 2 last items appear after the crash, but they're the same as when I close the software. I've looked for log files couldn't find them, could you point me in the right direction ?

Thanks a lot !

**Comment by bloopclick** [comment]
Does it say anything else or pop up a crash message, or does the window just close?

**Comment by Actual-Guilll** [comment]
No, it just closes. To clarify, it only happens on the "effect command select/help" page. On this page it always crashes after a few seconds, except if I keep moving my cursor using the arrow keys, then it doesn't crash, but it does as soon as I stop moving the cursor. Very strange.
I'm on Zorin 16 (a derivate of Ubuntu 20), and I'm using Pipewire.

**Comment by laamaa** [comment]
On one system I had the OS randomly send SDL_QUIT triggering events. Never found out why but commenting out https://github.com/laamaa/m8c/blob/main/input.c#L372 from the code helped with that. Since the program seems to exit cleanly it might be something similar.

**Comment by andreacampi** [comment]
Hah interesting, I'm experiencing exactly the same, only on the "secret help menu" page.

**Comment by yatli** [comment]
https://github.com/laamaa/m8c/pull/79/files

A fix is on the way!

**Comment by laamaa** [comment]
This should be fixed by #82
