### ISSUE TITLE
m8c failed to running

### ISSUE THREAD

**Issue by shanfei1985** [laamaa/m8c#85]
Hallo, 
Here is the error.

cpi@fei20th:~/app/m8c$ ./m8c
INFO: Reading config /home/cpi/.local/share/m8c/config.ini
INFO: Writing config file to /home/cpi/.local/share/m8c/config.ini
INFO: Looking for USB serial devices.
INFO: Found M8 in /dev/ttyACM1.
INFO: Opening port.
ERROR: Error: Failed: Inappropriate ioctl for device

cpi@fei20th:~/app/m8c$ sudo LIBSERIALPORT_DEBUG=1 m8c
INFO: Reading config /root/.local/share/m8c/config.ini
INFO: Writing config file to /root/.local/share/m8c/config.ini
INFO: Looking for USB serial devices.
sp: sp_list_ports(0xffffdc5b6650) called.
sp: Enumerating ports.
sp: Enumerating tty devices.
sp: Iterating over results.
sp: Found device /dev/ttyS6.
sp: serial8250 device, attempting to open.
sp: Port type is unknown, skipping.
sp: Found device /dev/ttyS4.
sp: serial8250 device, attempting to open.
sp: Port type is unknown, skipping.
sp: Found device /dev/ttyS2.
sp: serial8250 device, attempting to open.
sp: Port type is unknown, skipping.
sp: Found device /dev/ttyACM0.
sp: Found port /dev/ttyACM0.
sp: sp_get_port_by_name(/dev/ttyACM0, 0xaaaac42fb300) called.
sp: Building structure for port /dev/ttyACM0.
sp: get_port_details returning SP_OK.
sp: sp_get_port_by_name returning SP_OK.
sp: Found device /dev/ttyS7.
sp: serial8250 device, attempting to open.
sp: Port type is unknown, skipping.
sp: Found device /dev/ttyS5.
sp: serial8250 device, attempting to open.
sp: Port type is unknown, skipping.
sp: Found device /dev/ttyS3.
sp: serial8250 device, attempting to open.
sp: Port type is unknown, skipping.
sp: Found device /dev/ttyS1.
sp: serial8250 device, attempting to open.
sp: Port type is unknown, skipping.
sp: Found device /dev/ttyACM1.
sp: Found port /dev/ttyACM1.
sp: sp_get_port_by_name(/dev/ttyACM1, 0xaaaac42fb308) called.
sp: Building structure for port /dev/ttyACM1.
sp: get_port_details returning SP_OK.
sp: sp_get_port_by_name returning SP_OK.
sp: sp_list_ports returning SP_OK.
sp: sp_get_port_transport(0xaaaac42fb6d0) called.
sp: sp_get_port_transport returning 1.
sp: sp_get_port_usb_vid_pid(0xaaaac42fb6d0) called.
sp: sp_get_port_usb_vid_pid returning SP_OK.
sp: sp_get_port_transport(0xaaaac42fb7d0) called.
sp: sp_get_port_transport returning 1.
sp: sp_get_port_usb_vid_pid(0xaaaac42fb7d0) called.
sp: sp_get_port_usb_vid_pid returning SP_OK.
sp: sp_get_port_name(0xaaaac42fb7d0) called.
sp: sp_get_port_name returning /dev/ttyACM1.
INFO: Found M8 in /dev/ttyACM1.
sp: sp_copy_port(0xaaaac42fb7d0, 0xffffdc5b6648) called.
sp: Copying port structure.
sp: sp_get_port_by_name(/dev/ttyACM1, 0xffffdc5b6648) called.
sp: Building structure for port /dev/ttyACM1.
sp: get_port_details returning SP_OK.
sp: sp_get_port_by_name returning SP_OK.
sp: sp_copy_port returning 0.
sp: sp_free_port_list(0xaaaac42fb300) called.
sp: Freeing port list.
sp: sp_free_port(0xaaaac42fb6d0) called.
sp: Freeing port structure.
sp: sp_free_port returning.
sp: sp_free_port(0xaaaac42fb7d0) called.
sp: Freeing port structure.
sp: sp_free_port returning.
sp: sp_free_port_list returning.
INFO: Opening port.
sp: sp_open(0xaaaac42fb8d0, 0x3) called.
sp: Opening port /dev/ttyACM1.
sp: get_config(0xaaaac42fb8d0, 0xffffdc5b6590, 0xffffdc5b6568) called.
sp: Getting configuration for port /dev/ttyACM1.
sp: get_flow(3, 0xffffdc5b6590) called.
sp: Getting advanced flow control.
sp: sp_last_error_message() called.
sp: sp_last_error_message returning Inappropriate ioctl for device.
sp: get_flow returning SP_ERR_FAIL: Getting termiox failed: Inappropriate ioctl for device.
sp: sp_free_error_message(Inappropriate ioctl for device) called.
sp: sp_free_error_message returning.
sp: get_config returning SP_ERR_FAIL.
sp: sp_close(0xaaaac42fb8d0) called.
sp: Closing port /dev/ttyACM1.
sp: sp_close returning SP_OK.
sp: sp_open returning SP_ERR_FAIL.
sp: sp_last_error_message() called.
sp: sp_last_error_message returning Inappropriate ioctl for device.
ERROR: Error: Failed: Inappropriate ioctl for device
sp: sp_free_error_message(Inappropriate ioctl for device) called.
sp: sp_free_error_message returning.

**Comment by laamaa** [comment]
Please see the pinned issue https://github.com/laamaa/m8c/issues/20

This is likely due to a conflict with your Linux kernel and libserialport.

**Comment by laamaa** [comment]
Closing as inactive
