### ISSUE TITLE
default keymap reflexion

### ISSUE THREAD

**Issue by farvardin** [laamaa/m8c#87]
hello,

After a while using m8c I've found it was easier to deal with this alternative keymap:

![image](https://user-images.githubusercontent.com/477243/187659282-c7e8717d-eb63-46fb-a9d9-858a20d351c0.png)

```
key_select_alt=29
key_start_alt=27
key_opt_alt=4
key_edit_alt=22
```

Similarly, with a controller like those cheap USB SNES like:

![image](https://user-images.githubusercontent.com/477243/187657378-7c4d777c-df25-49d3-b7ad-c295497e7b9b.png)

```
gamepad_select=0
gamepad_start=1
gamepad_opt=2
gamepad_edit=3
```

why?

because the original DirtyWave M8 is using this key setting:

![image](https://user-images.githubusercontent.com/477243/187657503-64117e50-05bd-4968-baae-b974473bb797.png)

This way, with this keymap, you'll get a closer experience. On the original PC keymap the row with option+edit and the row with shitf+play are inverted, which is a bit confusing when reading the documentation with the shortcuts for example...

just my 2 cents

btw many thanks for m8c, it's an awesome frontend to my teensy!

**Comment by laamaa** [comment]
Makes sense, I probably didn't give too much thought to the keyboard controls originally as I was using a NES gamepad. 

What do others think, should the default config be changed?

**Comment by laamaa** [comment]
I changed the default keyboard layout as suggested, but left the gamepad layout as is for now, since I think  those changes might not work super well on all gamepads
