### ISSUE TITLE
m8c autorun for RPI

### ISSUE THREAD

**Issue by RAWJUNGLE** [laamaa/m8c#88]
sudo /home/pi/code/m8c/m8c - not working

maybe I'm doing something wrong?

**Comment by zsoltmar** [comment]
./home/pi/code/m8c/m8c - don't forget the dot in the beginning

**Comment by laamaa** [comment]
You shouldn't need to use sudo to start the program if your user has access to the serial device, often by belonging to the group plugdev. 

Unfortunately implementing automatic program starting isn't really a m8c issue, as it depends mostly on your OS distribution and installed software. I personally have used .bashrc and .xinitrc for starting m8c on minimal machines that were specifically configured for the tasks, but there's a lot of different ways to do it and it really depends on your system what's the best.
