### ISSUE TITLE
Audio routing startup script

### ISSUE THREAD

**Issue by zsoltmar** [laamaa/m8c#89]
I have Jackd routing the audio, I added the commands from the readme in a script and it works when I run the script manually. However when I try to add this script to be executed at boot by rc.local it just doesn't want to run. Is there some trick to this? It's pretty annoying to have to initiate the script manually in order to get some sound after every restart. Any tips?

**Comment by laamaa** [comment]
(sorry, now that I think of it I'm not sure if routing audio between interfaces works like that outside of Pipewire)
